// Auto-generated by scripts/generateStorybook.js

export const loadStories = () => {
  require("../src/components/Button/Button.stories.tsx")
  require("../src/components/ListRow/ListRow.stories.tsx")
  require("../src/components/Text/Body.stories.tsx")
  require("../src/components/Text/Heading.stories.tsx")
  require("../src/screens/Planets/InfoSection.stories.tsx")
}
